from fastapi import FastAPI, HTTPException, Depends, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from openpyxl import Workbook
from openpyxl.styles import Font
import io

from sqlalchemy.orm import Session
from database import SessionLocal, engine, Base
import models
import schemas


# Kreiramo tabele
Base.metadata.create_all(bind=engine)

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Dependency
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# CREATE
@app.post("/items/", response_model=schemas.Item)
def create_item(item: schemas.ItemCreate, db: Session = Depends(get_db)):
    db_item = models.Item(**item.dict())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item

# READ (filter + pagination)
@app.get("/items/")
def read_items(
    skip: int = 0, 
    limit: int = 10,
    search: str = Query("", description="Search by name"),
    db: Session = Depends(get_db)
):
    query = db.query(models.Item).filter(models.Item.name.contains(search))

    total = query.count()

    items = query.offset(skip).limit(limit).all()

    return {
        "items": items,
        "total": total
    }

# READ single
@app.get("/items/{item_id}", response_model=schemas.Item)
def read_item(item_id: int, db: Session = Depends(get_db)):
    item = db.query(models.Item).get(item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item

# UPDATE
@app.put("/items/{item_id}", response_model=schemas.Item)
def update_item(item_id: int, item: schemas.ItemCreate, db: Session = Depends(get_db)):
    db_item = db.query(models.Item).get(item_id)
    if not db_item:
        raise HTTPException(status_code=404, detail="Item not found")
    db_item.name = item.name
    db_item.description = item.description
    db.commit()
    db.refresh(db_item)
    return db_item

# DELETE
@app.delete("/items/{item_id}")
def delete_item(item_id: int, db: Session = Depends(get_db)):
    db_item = db.query(models.Item).get(item_id)
    if not db_item:
        raise HTTPException(status_code=404, detail="Item not found")
    db.delete(db_item)
    db.commit()
    return {"detail": "Item deleted"}

# Downloads PDF
@app.get("/items/download/pdf")
def download_items_pdf(db: Session = Depends(get_db)):
    items = db.query(models.Item).all()

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=80,
        bottomMargin=60,
    )

    styles = getSampleStyleSheet()
    elements = []

    # HEADER
    title = Paragraph("<b>Items Report</b>", styles["Title"])
    elements.append(title)

    elements.append(Paragraph(" ", styles["Normal"]))

    # TABLE DATA
    table_data = [["ID", "Name", "Description"]]

    for item in items:
        table_data.append([item.id, item.name, item.description])

    table = Table(table_data, colWidths=[50, 150, 250])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
    ]))

    elements.append(table)

    # FOOTER + PAGE NUMBER
    def add_footer(canvas, doc):
        canvas.setFont("Helvetica", 9)
        canvas.drawString(40, 30, "Generated by CRUD App")
        canvas.drawRightString(
            A4[0] - 40,
            30,
            f"Page {doc.page}"
        )

    doc.build(elements, onLaterPages=add_footer, onFirstPage=add_footer)

    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=items.pdf"},
    )

# Downloads Excel
@app.get("/items/download/excel")
def download_items_excel(db: Session = Depends(get_db)):
    items = db.query(models.Item).all()

    wb = Workbook()
    ws = wb.active
    ws.title = "Items"

    headers = ["ID", "Name", "Description"]
    ws.append(headers)

    for cell in ws[1]:
        cell.font = Font(bold=True)

    for item in items:
        ws.append([item.id, item.name, item.description])

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": "attachment; filename=items.xlsx"},
    )
